{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alertmanager-sms.serviceAccountName" . }}
  {{ include "alertmanager-sms.namespace" . }}
  labels:
    {{- include "alertmanager-sms.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
