---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: alertmanager-sms
  name: alertmanager-sms
  namespace: monitoring
spec:
  selector: 
    app: alertmanager-sms
    version: stable   
  ports:            
  - name: http 
    port: 5001      
    protocol: TCP 
    targetPort: 5001 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: alertmanager-sms
    version: stable
  name: alertmanager-sms
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: alertmanager-sms
      version: stable
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: alertmanager-sms
        version: stable
    spec:
      containers:
      - name: alertmanager-sms
        image: registry.cdtft.cn/base/alertmanager-sms
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5001
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 5001
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: '0.5'
            memory: 100Mi
          requests:
            cpu: '0.5'
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: alertmanager-sms-config
          mountPath: /opt/python/config 
          readOnly: true
        - name: timezone
          mountPath: /etc/localtime 
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name:  alertmanager-sms-config
        configMap:
          name: alertmanager-sms-config
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
